GitHub CI: ensure setuptools is installed
Looks like setuptools is no longer installed by default on recent
Python versions - 3.12 more precisely:
https://github.com/iustin/pyxattr/actions/runs/7236053321/job/19714175539,
which says:

```
Run python ./setup.py build_ext -i
Traceback (most recent call last):
  File "/Users/runner/work/pyxattr/pyxattr/./setup.py", line 5, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
```

So let's explicitly install it for CI runs.